# Generated by Django 5.1.3 on 2024-12-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GinaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
